version: 0.2
env:
  secrets-manager:
    DOCKERHUB_PASS: "DLogin:PASSWD"
    DOCKERHUB_USERNAME: "DLogin:USER"
phases:
  build:
    commands:
      - echo Building budgetCompanionNginx, budgetCompanionFrontend, and budgetCompanionBackend images
      - echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - docker build -t ardiank/budgetcompanionnginx -f ./nginx/Dockerfile ./nginx
      - docker build -t ardiank/budgetcompanionfrontend ./frontend
      - docker build -t ardiank/budgetcompanionbackend ./backend
  post_build:
    commands:
      - echo Pushing images to Docker Hub
      - docker push ardiank/budgetcompanionnginx
      - docker push ardiank/budgetcompanionfrontend
      - docker push ardiank/budgetcompanionbackend