version: '3.3'
services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  client:
      build: 
        context: ./frontend
        dockerfile: Dockerfile
      container_name: frontend

  backend:
      build: 
        context: ./backend
        dockerfile: Dockerfile
      container_name: backend